[package]
name = "cairo_wave"
version = "0.1.0"
authors = ["Tekkac <tekkac@proton.me>"]
edition = '2023_10'

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = ">=2.6.0"
koji = { git = "https://github.com/cienicera/Koji.git" }