[package]
name = "cairo_wave"
version = "0.1.0"
authors = ["Tekkac <tekkac@proton.me>"]
edition = '2024_07'

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = ">=2.8.5"
cubit = "1.3.1"
# koji = { git = "https://github.com/cienicera/Koji.git" }

[dev-dependencies]
cairo_test = "2.8.5"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.33.0" }

[scripts]
test = "snforge test --max-n-steps 4294967295"